### ISSUE TITLE
Broken links to Workaholics Anonymous PDFs

### ISSUE THREAD

**Issue by illright** [michellebakels/dev-health-os#2]
I'm not sure if this is the right place to post feedback about https://www.devhealthos.com/, but I noticed that the [CC2 page of the workbook](https://www.devhealthos.com/workbook/cerebral-calisthenics/cc2) contained links to PDFs from Workaholics Anonymous that are no longer there:
- [Workaholics Anonymous Sign Posts](https://workaholics-anonymous.org/pdf_files/signposts.pdf)
- [Workaholics Anonymous Knowing](http://www.workaholics-anonymous.org/pdf_files/knowing.pdf)

**Comment by michellebakels** [comment]
Thank you so much for bringing this to my attention! The broken links have been replaced on this page: https://www.devhealthos.com/workbook/cerebral-calisthenics/cc2. 🙏

**Comment by illright** [comment]
Sorry, forgot to mention that there's another page that links to these PDFs:

https://www.devhealthos.com/os/section1/tasha
